PERMISSION_GROUPS = {
    "CODES": ["CODES_REDEEM", "CODES_STATUS", "CODES_QUEUE_VIEW"],
    "PLAYERS": ["PLAYERS_VIEW", "PLAYERS_DISABLE"],
    "SECURITY": ["SECURITY_SCAN", "SECURITY_AUDIT_VIEW", "SECURITY_INCIDENTS_VIEW", "SECURITY_BLOCKED_VIEW"],
    "SYSTEM": ["SYSTEM_VIEW", "SYSTEM_DIAGNOSTICS", "SYSTEM_INTEGRITY", "SYSTEM_AUTOPILOT", "SYSTEM_WATCHDOG", "SYSTEM_PREDICT"],
    "BACKUP": ["BACKUP_CREATE", "BACKUP_LIST", "ROLLBACK_EXECUTE"],
    "UPDATES": ["UPDATES_CHECK", "UPDATES_PLAN", "UPDATES_APPLY"],
    "MAINTENANCE": ["MAINTENANCE_CLEANUP", "MAINTENANCE_RETRY", "MAINTENANCE_LOGS_VIEW"],
    "ADMINISTRATION": [
        "ADMINS_VIEW", "ADMINS_CREATE", "ADMINS_UPDATE", "ADMINS_DELETE",
        "SUPERVISORS_VIEW", "SUPERVISORS_CREATE", "SUPERVISORS_UPDATE", "SUPERVISORS_DELETE",
        "SETTINGS_VIEW", "SETTINGS_UPDATE", "OWNER_SETTINGS_VIEW"
    ],
    "ALLIANCE": [
        "ALLIANCE_VIEW", "ALLIANCE_CREATE", "ALLIANCE_UPDATE", "ALLIANCE_DISABLE",
        "ALLIANCE_MEMBERS_VIEW", "ALLIANCE_MEMBER_ASSIGN", "ALLIANCE_MEMBER_REMOVE", "ALLIANCE_MEMBER_RANK_UPDATE",
        "ALLIANCE_STATS_VIEW", "ALLIANCE_AUDIT_VIEW",
        "ALLIANCE_API_VIEW", "ALLIANCE_API_CONFIG", "ALLIANCE_API_SYNC", "ALLIANCE_API_AUTO_SYNC_TOGGLE", "ALLIANCE_API_HEALTH",
    ],
    "CONTENT": [
        "CONTENT_VIEW", "CONTENT_EDIT", "CONTENT_RESET", "CONTENT_AUDIT_VIEW",
    ],
}

ALL_PERMISSIONS = [
    "PANEL_VIEW",
    "CODES_REDEEM", "CODES_STATUS", "CODES_QUEUE_VIEW",
    "PLAYERS_VIEW", "PLAYERS_DISABLE",
    "SECURITY_SCAN", "SECURITY_AUDIT_VIEW", "SECURITY_INCIDENTS_VIEW", "SECURITY_BLOCKED_VIEW",
    "SYSTEM_VIEW", "SYSTEM_DIAGNOSTICS", "SYSTEM_INTEGRITY", "SYSTEM_AUTOPILOT", "SYSTEM_WATCHDOG", "SYSTEM_PREDICT",
    "BACKUP_CREATE", "BACKUP_LIST", "ROLLBACK_EXECUTE",
    "UPDATES_CHECK", "UPDATES_PLAN", "UPDATES_APPLY",
    "MAINTENANCE_CLEANUP", "MAINTENANCE_RETRY", "MAINTENANCE_LOGS_VIEW",
    "ADMINS_VIEW", "ADMINS_CREATE", "ADMINS_UPDATE", "ADMINS_DELETE",
    "SUPERVISORS_VIEW", "SUPERVISORS_CREATE", "SUPERVISORS_UPDATE", "SUPERVISORS_DELETE",
    "SETTINGS_VIEW", "SETTINGS_UPDATE", "OWNER_SETTINGS_VIEW",
    "ALLIANCE_VIEW", "ALLIANCE_CREATE", "ALLIANCE_UPDATE", "ALLIANCE_DISABLE",
    "ALLIANCE_MEMBERS_VIEW", "ALLIANCE_MEMBER_ASSIGN", "ALLIANCE_MEMBER_REMOVE", "ALLIANCE_MEMBER_RANK_UPDATE",
    "ALLIANCE_STATS_VIEW", "ALLIANCE_AUDIT_VIEW",
    "ALLIANCE_API_VIEW", "ALLIANCE_API_CONFIG", "ALLIANCE_API_SYNC", "ALLIANCE_API_AUTO_SYNC_TOGGLE", "ALLIANCE_API_HEALTH",
    "CONTENT_VIEW", "CONTENT_EDIT", "CONTENT_RESET", "CONTENT_AUDIT_VIEW",
]

ADMIN_DEFAULT_PERMISSIONS = [
    "PANEL_VIEW", "CODES_STATUS", "CODES_QUEUE_VIEW",
    "PLAYERS_VIEW", "SYSTEM_VIEW",
    "BACKUP_LIST", "MAINTENANCE_LOGS_VIEW", "SETTINGS_VIEW",
    "ALLIANCE_VIEW", "ALLIANCE_MEMBERS_VIEW", "ALLIANCE_STATS_VIEW",
    "ALLIANCE_API_VIEW", "ALLIANCE_API_HEALTH",
    "CONTENT_VIEW",
]

SUPERVISOR_DEFAULT_PERMISSIONS = [
    "PANEL_VIEW", "CODES_STATUS", "CODES_QUEUE_VIEW", "PLAYERS_VIEW",
    "ALLIANCE_VIEW", "ALLIANCE_MEMBERS_VIEW", "ALLIANCE_STATS_VIEW",
]

OWNER_IMPLICIT_PERMISSIONS = ALL_PERMISSIONS.copy()

ROLE_LEVELS = {
    "OWNER": 3,
    "ADMIN": 2,
    "SUPERVISOR": 1,
}

ADMIN_LEVEL = "ADMIN"
SUPERVISOR_LEVEL = "SUPERVISOR"
OWNER_LEVEL = "OWNER"
